### ISSUE TITLE
CAppUI.class.php enabled use @ in login name

### ISSUE THREAD

**Issue by mtzlobr** [web2project/web2project#286]
Hi,
can you pleas modify CAppUI.class.php as follow bellow.  
  
$username = preg_replace("/[^A-Za-z0-9._@-]/", "", $username);

Thanks 
Mirek

**Comment by caseysoftware** [comment]
:+1: I'll add this over the weekend.

**Comment by caseysoftware** [comment]
Resolved in master here:
https://github.com/web2project/web2project/commit/90639f8c1a0b1dda35dfcf2d44fb3a07eaa5543b
