### ISSUE TITLE
Installer does not create database

### ISSUE THREAD

**Issue by moisseev** [web2project/web2project#288]
After pressing ```install db only``` or ```install db and write cfg``` in ```Step 2: Database Settings```
the installer does not create database or config file and shows blank window just with header:
```
Welcome to the web2Project Update Manager!
This system will help you perform ... then we'll load the system.
```
I have the issue with release 3.2 and later including master.
```
 # uname -mrs
FreeBSD 10.1-RELEASE i386
# pkg info -q | egrep '(php|apache)'
apache24-2.4.12
mod_php56-5.6.8
php56-5.6.8
php56-gd-5.6.8
php56-mysql-5.6.8
php56-session-5.6.8
php56-zlib-5.6.8
```

**Comment by caseysoftware** [comment]
The system does not create the database on its own. See Step 3 of the installation instructions: http://wiki.web2project.net/index.php?title=Installation (linked from the README)

**Comment by moisseev** [comment]
Of course I have created a blank database before run the installer:
```
mysql> CREATE DATABASE web2project;
mysql> use web2project;
mysql> GRANT ALL PRIVILEGES ON web2project.* TO web2project@localhost IDENTIFIED BY 'password';
mysql> flush privileges;
mysql> quit
```

**Comment by caseysoftware** [comment]
Are you getting any messages in your PHP error logs?

Alternatively, can you turn on debug mode and share the error?

Change the zero to a one here:
https://github.com/web2project/web2project/blob/master/base.php#L6

**Comment by moisseev** [comment]
I have set ```ini_set('display_errors', 1);``` in base.php
After 'Step 2: Database Settings' was completed I got this page:
![Uploading 2015-05-27 17_36_41-web2Project Update Manager - Pale Moon.png…]()
No errors has been written into web-server log.

**Comment by moisseev** [comment]
Mysql driver had switched to mysqli after 3.1 release. In later versions installer hangs with no error if mysql driver is used instead of mysqli.
