### ISSUE TITLE
What is default password?

### ISSUE THREAD

**Issue by aghict** [web2project/web2project#291]
Hello,
I install W2P now I don't know what is admin password?

**Comment by caseysoftware** [comment]
passwd

All lower case. It's on the success screen post install too:
https://github.com/web2project/web2project/blob/00ba1238bfe198378483e1bdab32ea2ba59f0501/install/install/dbcreds.php#L55

(Also, sorry that I didn't respond sooner. I never got a notification on this message. :( )
