### ISSUE TITLE
Web2project 3.3.66 - general PHP error : Undefined index: project_end_date

### ISSUE THREAD

**Issue by fscoelho** [web2project/web2project#297]
Hello, 
I am trying to use web2project instead dotproject , i create a project with one task only with a defined date, but when i go to mytasks->Mygantt  i get the error 
"general PHP error : Undefined index: project_end_date"
Web2project 3.3.66
What is wrong ?

Waiting answer soon best regards, 
F. Coelho

**Comment by opto** [comment]
I think there are database sql updates which you need to do, if you upgrade from dP to w2p.

**Comment by caseysoftware** [comment]
I'm closing this one since it's been 6+ months without update.

I hope Coelho figured out and solved the issue. If not, happy to pick it up again.
