### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by tastymousehub** [web2project/web2project#299]
Hi, since there isn't a forum anymore I put my question here. I have to change from DotProject because it doesn't work with PHP7. So my question is: will WEB2PROJECT work with php7?

**Comment by caseysoftware** [comment]
I'm working to bring the forum back online this weekend.

I have not tested w2p with php7 but it's on my todo list.

**Comment by tastymousehub** [comment]
Great, thanks.

**Comment by opto** [comment]
there was a thread by sasquatch in the forum on php7. Mainly, it is running, but for some things he wrote in that post.

**Comment by tastymousehub** [comment]
Okay, i'll do another search, thanks for mentioning it.

**Comment by caseysoftware** [comment]
The forum is still offline. I'm trying to bring it back online now.

**Comment by caseysoftware** [comment]
The support site is back online. Here's the relevant thread: http://support.web2project.net/questions/2996/install-web2project-with-php7

**Comment by tastymousehub** [comment]
Thanks, Tom
