### ISSUE TITLE
migrating server problem with accent mark

### ISSUE THREAD

**Issue by jbarbaran** [web2project/web2project#301]
Hello,

We are having Web2Project since 5 years ago. Now we have migrated to a new server, from Windows Server 2008 to Windows server 2012 r2. The problem we are having is that task, projects, companies in spanish have accent mark á, é.. so on. When we have moved the web2project, files and database with no problems but when we log in we see task names, user names, companies, ... where there is a accent mark the following icon �

What might be the problem? We tried changing the charset of the database, the config file for web2project with no solution.

Thank you very much in advance.

Regards

**Comment by caseysoftware** [comment]
Did you change your versions of MySQL and PHP also? What versions were you on and what versions did you upgrade to?

**Comment by jbarbaran** [comment]
The version we are running are the following:
MySQL 5.5.54
PHP 5.4.45

Apparently seems that it is a problem with encoding but I can't figure out why is it happening on this server...

I would appreciate any ideas!!

Thanks!

**Comment by jan-b** [comment]
Hi jbarbaran

I have had similar encoding problems several times with other databases.
Most exports of MySQL is taking care of the charset specified in tables, for example DEFAULT CHARSET=utf8, but sometimes this can fail when exporting databases using another character set for the sql file itself. 
As an example using tables in utf-8 and export from phpmyadmin in file charset iso-8859-1
The first thing I usually does is to check the sql file itself before import to be sure the correct encoding is in use. If this is wrong, make a copy of the sql file (important!!!) and try to change the file encoding using for example Notepad++ if the charset is wrong ( i am sure there is other tools that can do the same job).
I think that more than 70% of all encoding problems i have had is utf-8 vs iso-8859 file format problems.
There may of course be other encoding problems as well.

If you can post some sample lines ( ziped) with accent mark from your sql file I can have a look at it if you want.

Jan

**Comment by 62BRAINS** [comment]
Are you running IIS, Apache, or Nginx as your web server? Was the 2012 r2 server freshly installed and configured or was it used for a different service prior to moving your Web2Project?

**Comment by jbarbaran** [comment]
@62BRAINS I'm running IIS and windows 2012 R2 was freshly installed. But we also host a Wordpress website which uses also PHP + MySQL, with no encoding problems so far... so I'm thinking that it might be a problem exporting the database.

**Comment by jbarbaran** [comment]
Hi Jan,

I think you are right, I will restart the old O.S. instance and try to
export the database again paying attention at the encoding selected.

Thank you very much!!!

Javier.

2017-04-13 22:13 GMT+02:00 Jan Bakke <notifications@github.com>:

**Comment by jbarbaran** [comment]
I finally got the solution, in my case the problem came with MySQL installation.
I have edited my.cnf file (located on MySQL installation folder) and changed charset from latin1 to utf8.

```
character-set-server=utf8
default-character-set=utf8
```
