### ISSUE TITLE
Developments for web2project

### ISSUE THREAD

**Issue by JorgeAlejandroAguirreGutierrez** [web2project/web2project#302]
We are Global Solutions Group SAS a Colombian business solutions consulting company, we decided to implement in our company web2project, during the implementation we have solved several problems among which they are: Error in the visualization of weekends in the weekly view, as the integration of the module holidays to the calendar and its monthly and annual weeks views. We are developing at the moment to solve errors that present the modules of help desk and flex report. I would like us to work collaboratively to improve the software and I would also kindly ask you if you have a user manual for all modules.

**Comment by opto** [comment]
you are welcome to send in any bug resolutions which you find. I can add them into the system.

For formal cooperation, you need to contact Keith.

Thanks, Klaus (=opto in forums)
