### ISSUE TITLE
Declaration of CEvent::loadFull($event_id) should be compatible with w2p_Core_BaseObject::loadFull

### ISSUE THREAD

**Issue by petermoo** [web2project/web2project#303]
Downloaded today. Fixed MySQL default date issue. The following warning appears in the log. PHP 7.0.22.

`PHP Warning:  Declaration of CEvent::loadFull($event_id) should be compatible with w2p_Core_BaseObject::loadFull($notUsed, $object_id) in public_html/modules/events/events.class.php on line 0`

public function loadFull($notUsed = null, $object_id) {     $this->load($object_id);        }

Doing a search for loadfull, there appear to be ten uses with only two using the null, addedit.php and vcardexport.php.

**Comment by caseysoftware** [comment]
Yes, this is a known warning that does not negatively affect the performance or behavior of the system.

The method is there for backwards compatibility and won't be removed until we start working on v4.0 development. But that will require at least one cleanup release before we get there.

**Comment by caseysoftware** [comment]
Resolved in the https://github.com/web2project/web2project/tree/php-8-compat branch
