### ISSUE TITLE
how to make user inactive

### ISSUE THREAD

**Issue by opto** [web2project/web2project#305]
I would expect a checkbox in user admin -> edit but there is none

**Comment by caseysoftware** [comment]
The actual approach is to just delete their permissions.

I agree with you though. It should be a toggle so that you can re-activate a user with the same permissions after.

**Comment by syanzy** [comment]
Yes. And there is a tab for inactive users. When does a user get moved to that tab?

**Comment by caseysoftware** [comment]
Once they have permissions (usually a Role) that allows it.

Some more details: http://docs.web2project.net/modules/user-admin.html
