### ISSUE TITLE
Unable to register for forum

### ISSUE THREAD

**Issue by patredmond** [web2project/web2project#306]
I realise this isn't really the best place for this, however I'm not sure where else to go...
It's not possible to register on the forum to ask a question - the recapture is broken.

![image](https://user-images.githubusercontent.com/1319787/35407701-ebc055c0-0260-11e8-81cc-365f5f522069.png)

**Comment by caseysoftware** [comment]
This looks like an intermittent error. Can you try again?

**Comment by patredmond** [comment]
Yep - it's working now. Thanks for the fast reply. :)
