### ISSUE TITLE
Doesn't run on LAMPP in Linux Mint and shows Access Forbidden ?

### ISSUE THREAD

**Issue by geekhaidar** [web2project/web2project#315]
Access forbidden!
You don't have permission to access the requested object. It is either read-protected or not readable by the server.

If you think this is a server error, please contact the webmaster.

Error 403
127.0.0.1
Apache/2.4.34 (Unix) OpenSSL/1.0.2p PHP/7.2.10 mod_perl/2.0.8-dev Perl/v5.16.3

![image](https://user-images.githubusercontent.com/42756579/46603405-97b5f600-cb10-11e8-8516-d3dfebff16a7.png)

**Comment by caseysoftware** [comment]
Sorry for the delay in getting back to you. Without some information such as PHP and apache config, I can't tell you what the issue might even be.
