### ISSUE TITLE
Change reset admin password

### ISSUE THREAD

**Issue by goran-mahovlic** [web2project/web2project#316]
I have web2project installed on my server for a long time.
And now I do not remember not admin password or any user password. 

I have tried request Help! I've forgotten my password! but does not work for me.
I have tried to find user and pass in mysql database, and did found that I have user admin, but how can I reset password for him...

**Comment by Themoulos** [comment]
- Find table \"users\" 
- Find the record of \"admin\" (usually user_id=1) 
- Open the SQL Tab of phpmyadmin 
- Enter the following: 
UPDATE users SET user_password=MD5('NEW PASSWORD HERE') WHERE user_id = 1; 
Then, try to login again. Tell me if it worked...

**Comment by goran-mahovlic** [comment]
I did not notice that there is more then one row of tables so at first I did not find user table.
I have changed pass and successfully login all is working now. 
Thank you for support.
