### ISSUE TITLE
Blank page on PHP 7.2

### ISSUE THREAD

**Issue by tastymousehub** [web2project/web2project#317]
When I update to php 7.2 I get a blank page, no warnings. Has anyone got it working with 7.2?

**Comment by caseysoftware** [comment]
Sorry for the delay on this one.. but I just figured out what it was:  https://github.com/web2project/web2project/commit/693e11330424066a482aeaccff250f5e2524d41a

**Comment by caseysoftware** [comment]
This will be in the next release asap.
