### ISSUE TITLE
error 500 php 7.2 version3.4

### ISSUE THREAD

**Issue by blekbokis** [web2project/web2project#318]
Hello everybody! Sorry for introducing my trouble and being such an embarrassing ignorant about coding and all its world... i just would need help after having upgraded in our cpanel from php 5.6 to php7.2 and discovering (after a while)  that web2project didn't work anymore (http error 500). I also found the new web2p release 3.4 and tried to install, but after having copying all files in the sub-directories the browser didn't allow going on trough the installation, giving the same error 500... i know someone had already similar problems, but still i don't know how to solve it. Please try to explain to super-dummies!
In the same public_html directory there is also a wordpress website (in a sub-directory) therefore there are also  3 free files : index.php , .htaccess, php.ini are they making problem too?
Many many thanks!

[error_log.txt](https://github.com/web2project/web2project/files/2765552/error_log.txt)

**Comment by caseysoftware** [comment]
The most likely problem is your database connection. In includes/config.php make sure that your $w2Pconfig['dbtype'] is set to mysqli.

**Comment by blekbokis** [comment]
Hi! Thank you so much for your answer! Yes i opened the config.php and there is written:
*/

$w2Pconfig['dbtype'] = 'mysql'

**Comment by blekbokis** [comment]
YES! YES! YES! You were right! I told you i am dummy! there is actually difference between mysql and mysqli  !! sorry i did't understand! Now it works!!!! Thank you again!!
