### ISSUE TITLE
Cannot create a project

### ISSUE THREAD

**Issue by pannonius** [web2project/web2project#321]
Click on New Project opens the New Project Form, and I can fill in  all information. After clicking on Save button, I got a "Connecting" and "Waiting for" server messages on the left bottom part of the Form, and a "https://freelancer.com/index.php?m=projects&a=addedit&project_id=0" address appears in the address bar (note that freelancer.com is not a really name of the server - I changed it for security reason) ...

Project is not saved, not created. The newly saved project is not listed in the project list - I can create any project!

Josip

**Comment by caseysoftware** [comment]
Without seeing your configuration, it's hard to diagnose but I'd wager the Site Domain in your System Configuration is incorrect.

**Comment by pannonius** [comment]
Well, let me tell You that I can create new Company, new Contact, new user, new folder and, also, to upload file to folder ... Is this all possible with incorrect Site Domain in System Configuration? And, if yes, how to fix this error?

**Comment by caseysoftware** [comment]
Hmmm.. That doesn't make sense then. That setting would apply to all situations.

It looks like there's an error in the save action and it's supposed to redirect back and display the error. The redirect is working but not the error display.  Check out the requirements of a Project - https://github.com/web2project/web2project/blob/master/modules/projects/projects.class.php#L61 - and make sure you have a name filled in, company selected, and color chosen. Then try to save.

**Comment by pannonius** [comment]
Hi!
I downloaded the project.class.php update, and tried to create project - filled in data every textbox and choose color. The contact have chosen from the chosen Company contacts .
.. The same result. Project is not saved, not created. The newly saved project is not listed in the project list - I can't create any project ...

**Comment by pannonius** [comment]
The web2project version is 3.4, PHP version is 7.2 ...

**Comment by pannonius** [comment]
The problem was that project_id field in the project table has not set AUTO INCREMENT property .... Setting it, the program is working like charm :)

**Comment by fritzratna** [comment]
Hi am having the similar issue. However, I do not see a table name just project. I see table names with these names : project_contacts, project_departments, project_designer_options. Whichi I should look at? Please help.Been struggling for many days

**Comment by caseysoftware** [comment]
Start fresh, do a git checkout or download from the repository (don't download the release), and try to install it that way.

**Comment by fritzratna** [comment]
Cool, works better when downloaded from repository. Can I add the command I used to install it ?
