### ISSUE TITLE
badly broken on php 7.3.2

### ISSUE THREAD

**Issue by opto** [web2project/web2project#322]
new install:
1) admin has no access rights
2) after first project is created: new project button opens form with data of this first project.  If project name and short name are changed, form reopens upon save with same data and no error message.
3) project appears in project list, but no right to access it. even grantig al rights on all modules and in addition on all projects does not help

**Comment by chdrsto** [comment]
Yep, i can confirm issues with PHP 7.3.4 as well.
Fresh install. Calling User admin page seems empty.

**Comment by opto** [comment]
problem is that first project that is created gets id of 0. That breaks our mechanism to distinguish new from old projects. Index should start at 1.

**Comment by chdrsto** [comment]
I just realized, that my issue with the admin page, appears on PHP 7.0.33 as well. So, not related to the PHP version. I guess broken 3.4 version.

**Comment by chdrsto** [comment]
I get following error:
`PHP Fatal error:  Uncaught Error: Call to undefined function mb_strpos() in /var/www/html/web2project-version3.4/modules/users/index.php:37\nStack trace:\n#0 /var/www/html/web2project-version3.4/index.php(252): require()\n#1 {main}\n  thrown in /var/www/html/web2project-version3.4/modules/users/index.php on line 37, referer: https://SERVER/?m=users`
or
`PHP Fatal error:  Uncaught Error: Call to undefined function mb_substr() in /var/www/html/web2project-version3.4/modules/projects/projects.class.php:417\nStack trace:\n#0 /var/www/html/web2project-version3.4/classes/w2p/Core/BaseObject.class.php(798): CProject->hook_preStore()\n#1 /var/www/html/web2project-version3.4/classes/w2p/System/Dispatcher.class.php(92): w2p_Core_BaseObject->publish(Object(w2p_System_Event))\n#2 /var/www/html/web2project-version3.4/classes/w2p/Core/BaseObject.class.php(333): w2p_System_Dispatcher->publish(Object(w2p_System_Event))\n#3 /var/www/html/web2project-version3.4/modules/projects/do_project_aed.php(20): w2p_Core_BaseObject->store()\n#4 /var/www/html/web2project-version3.4/index.php(225): require('/var/www/html/w...')\n#5 {main}\n  thrown in /var/www/html/web2project-version3.4/modules/projects/projects.class.php on line 417, referer: https://SERVER/index.php?m=projects&a=addedit`

**Comment by opto** [comment]
if you use git, go back one commit (see my extra issue 323).
Also, in table projects, project_id must be autoincrement in extra (see structure of table in phpmyadmin

didn't fully test whether there are other issues

**Comment by chdrsto** [comment]
yes, but it seems that the project tasks are no more editable without using the Project Designer.
Using "New Task" in a fresh Project end up in a timout. Anybody confirm?

**Comment by opto** [comment]
works here on xampp on win10, if this commit is reverted: * locking the basic config

and if project_id is autoincrement:  ALTER table projects CHANGE project_id project_id    int(10) NOT NULL auto_increment

**Comment by caseysoftware** [comment]
Lots of fixes now on `php-8-compat` and will be rolled to master soon.
