### ISSUE TITLE
autoload_static.php missing + workaround

### ISSUE THREAD

**Issue by gregtampa** [web2project/web2project#330]
PHP Warning:  require_once(/var/www/vendor/composer/autoload_static.php): failed to open stream: No such file or directory in /var/www/vendor/composer/autoload_real.php on line 28

**Comment by opto** [comment]
reason: $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') && (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());

this is false, e.g. on xampp 7.0.32. It seems now zend_loader_file_encoded exists only on non thread safe PHP.

WORKAROUND: 
in vendor/composer/autoload_real.php, force $useStaticLoader to false:
$useStaticLoader  = false;

not helping: just to add autoload_static.php from the web. There, the $FILES are missing. One might need to rerun composer, but the workaround above helps.

Klaus

**Comment by caseysoftware** [comment]
You can resolve this one by going to the command line, going into your web2project folder and running:

`composer update`

It will update and/or create the files as necessary.
