### ISSUE TITLE
HTTP error 500 when importing tasks

### ISSUE THREAD

**Issue by alexjmetcalfe** [web2project/web2project#338]
hi,

We are getting HTTP 500 / WSOD when importing tasks into a project.

This is a sample error message from the server log.

[Wed Jan 20 11:35:24.770377 2021] [:error] [pid 18024] [client 10.30.208.6:59327] PHP Strict Standards:  Declaration of CDepartment::getAllowedRecords() should be compatible with w2p_Core_BaseObject::getAllowedRecords($uid, $fields = '*', $orderby = '', $index = NULL, $extra = NULL, $table_alias = '') in /srv/pruse/modules/departments/departments.class.php on line 0, referer: http://pruse.xxxx.xxxx/index.php?m=projects&a=view&project_id=799

Comments/advice/support welcome.

- Alex

**Comment by caseysoftware** [comment]
What version of PHP are you on?
