### ISSUE TITLE
Error: Failed opening required '/var/www/html/web2project/vendor/composer/platform_check.php'

### ISSUE THREAD

**Issue by jan-b** [web2project/web2project#347]
Stange!
I've got "This page isn’t working" on a fresh insall.
From Apache error log;
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/web2project/vendor/composer/platform_check.php'
..but it's there.
I'm running php 8.2 on Debian bullseye

**Comment by cjturner** [comment]
Make sure web server account and/or group (usually apache:apache) has access to the file & path.

**Comment by jan-b** [comment]
I've checked that.

**Comment by jan-b** [comment]
I've also set chmod -R 777 to the whole web2project map

**Comment by cjturner** [comment]
Look at TODO, Casey is working on PHP8 compatibility issues "as we speak."  He may respond, or you could try downloading that branch, but it looks not complete from his notes.

**Comment by caseysoftware** [comment]
What is the url of the page you're actually hitting?

**Comment by jan-b** [comment]
platform_check.php is actual missing from repository as well as
include_paths.php

**Comment by jan-b** [comment]
Ok, thanks.
I was thinking to contribute if I've was able to :)

**Comment by caseysoftware** [comment]
I'd love a hand but it'd be useful if I knew what URL you were on.
What url is in your browser when you get that error?

**Comment by jan-b** [comment]
On the default web2project.
I have updated config.php, ang got an "fatal error" by config PhP didn't
exist.
Before that I was re-routed to the install

**Comment by caseysoftware** [comment]
On the command line, go into your web2project directory and run:
`composer update` or the equivalent based on your composer install.

**Comment by jan-b** [comment]
Argh!

**Comment by jan-b** [comment]
Problem 1
    - phploc/phploc[4.0.0, ..., 4.0.1] require php ^5.6 || ^7.0 -> your php
version (8.2.14) does not satisfy that requirement.
    - Root composer.json requires phploc/phploc 4.* -> satisfiable by
phploc/phploc[4.0.0, 4.0.1].

**Comment by jan-b** [comment]
I've tried to downgrade to php7.4, but run into other problems reg.
extensions

**Comment by jan-b** [comment]
Composer version 2.5.8 installed

**Comment by jan-b** [comment]
Had to enable php7.2
composer --ignore-platform-req=ext-dom update
Then enabled php8.2 again
That worked!

**Comment by caseysoftware** [comment]
https://github.com/web2project/web2project/issues/346
