### ISSUE TITLE
On empty table

### ISSUE THREAD

**Issue by jan-b** [web2project/web2project#348]
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/web2project/classes/w2p/Output/ListTable.class.php:59\nStack trace:\n#0 /var/www/html/web2project/modules/tasks/todo_tasks_sub.php(129): w2p_Output_ListTable->buildRows()\n#1 /var/www/html/web2project/modules/tasks/todo.php(127): include('...')\n#2 /var/www/html/web2project/modules/events/vw_day_tasks.php(32): include('...')\n#3 /var/www/html/web2project/style/web2project/overrides.php(102): require('...')\n#4 /var/www/html/web2project/modules/events/day_view.php(94): CTabBox->show()\n#5 /var/www/html/web2project/index.php(252): require('...')\n#6 {main}\n  thrown in /var/www/html/web2project/classes/w2p/Output/ListTable.class.php on line 59

**Comment by caseysoftware** [comment]
Check out the https://github.com/web2project/web2project/commits/php-8-compat/ branch as this one is resolved
