### ISSUE TITLE
web2project/?m=forums

### ISSUE THREAD

**Issue by jan-b** [web2project/web2project#349]
Undefined variable $tab in /var/www/html/web2project/modules/forums/index.php on line 51, referer: http://192.168.1.5/web2project/?m=system
 The same here;
 PHP Warning:  Undefined variable $tab in /var/www/html/web2project/modules/tasks/index.php on line 69, referer: http://192.168.1.5/web2project/?m=events

**Comment by caseysoftware** [comment]
Warnings in the logs are simply informational. They should not be blocking your installation or usage.

That said, I'm working to clean these up but they're secondary to block issues.
